"""Add therapist fields to users table

Revision ID: 8ac1330fabcf
Revises: 
Create Date: 2025-04-03 09:13:58.499838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac1330fabcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # First add role as nullable
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        # Add other columns
        batch_op.add_column(sa.Column('specialization', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('years_of_experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hourly_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('qualifications', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # Update existing rows to have 'patient' role
    op.execute("UPDATE users SET role = 'patient' WHERE role IS NULL")
    
    # Make role non-nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_verified')
        batch_op.drop_column('languages')
        batch_op.drop_column('qualifications')
        batch_op.drop_column('profile_image')
        batch_op.drop_column('availability')
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('years_of_experience')
        batch_op.drop_column('bio')
        batch_op.drop_column('specialization')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
